### ISSUE TITLE
a param for changing font family?

### ISSUE THREAD

**Issue by shrektan** [ricardo-bion/ggradar#1]
Hi, thanks for this package. It's pretty cool.

However, I notice that you hard-coded the font family in function `ggradar` ( `family="Circular Air Light"` ) without allowing users to assign their preferred font (correct me if I'm wrong), which is inconvenient for users (e.g., I want use a Chinese font).

Is there any specific reason that the family has to be hard-coded?

Thanks.

**Comment by ricardo-bion** [comment]
Changed it here:

https://github.com/ricardo-bion/ggradar/blob/master/R/ggradar.R#L10

You can now enter any font in your system. e.g., `ggradar(mtcars_radar, font.radar = "Times")`

**Comment by shrektan** [comment]
Thanks :D
