### ISSUE TITLE
Issue using Circular Air-Light 3.46.45 PM.ttf font on Windows10 PC

### ISSUE THREAD

**Issue by VikrantDogra** [ricardo-bion/ggradar#14]
Can't use Circular Air-Light 3.46.45 PM.ttf font on Windows10 PC.
Used Microsoft Font Validator on this font.
Get the following error message: 
"The file was not recognized as a valid OpenType font file".

**Comment by JeffreyCKennedy** [comment]
Same issue here - Windows 10 gives message "does not appear to be a valid font".
![image](https://user-images.githubusercontent.com/15186676/35660333-487ed9c6-0770-11e8-9851-73ae902c2d58.png)

**Comment by fbreitwieser** [comment]
Similar errors on OSX. Please consider using a standard font by default.

```
30: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "Circular Air Light"
...
```

Its installation fails:

```
> download.file("https://github.com/ricardo-bion/ggtech/blob/master/Circular%20Air-Light%203.46.45%20PM.ttf", "~/Circular Air-Light 3.46.45 PM.ttf", method="curl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32609    0 32609    0     0   113k      0 --:--:-- --:--:-- --:--:--  113k
> 
> extrafont::font_import(pattern = 'Circular', prompt=FALSE)
Scanning ttf files in /Library/Fonts/, /System/Library/Fonts, ~/Library/Fonts/ ...
Extracting .afm files from .ttf files...
Error in data.frame(fontfile = ttfiles, FontName = "", stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 0, 1
```

**Comment by Rmadillo** [comment]
@fbreitwieser that error occurs because that font isn't in your fonts directory, you probably downloaded it to a different directory so the call to `font_import` can't find it. I did that but then got a warning from my Mac telling me the font had "critical errors" and I could mess up my system (!) if I installed it.

So instead, I just forked this repo, changed line 10 to `font.radar="Arial",` and installed from my repo instead of this one. I changed nothing else, and it works fine with Arial font. 

HTH.

**Comment by GaelleMG** [comment]
@Rmadillo how does one install from a local repo?  
I forked this repo, changed line 10 as you mentioned, but cannot install from my repo.  
If I try to build it, I get the error: 
cannot open file '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ggradar/R/ggradar.rdb': No such file or directory

**Comment by Rmadillo** [comment]
Fork it to your github account (not local), change line 10 there, and then run this from R:

```devtools::install_github("GaelleMG/ggradar")```

or, just install it from mine:

```devtools::install_github("rmadillo/ggradar")```

Lemme know if that doesn't work?

**Comment by ricardo-bion** [comment]
fixed

**Comment by 1beb** [comment]
I think for most people, they can get the font easier if they just remove `~/` from your instructions. That at least leaves it in the current working directory.
