### ISSUE TITLE
Legend still showing although plot.legend=FALSE

### ISSUE THREAD

**Issue by kielhauser** [ricardo-bion/ggradar#17]
Thanks for this package!
I am trying to produce a radar chart without a legend, but somehow the legend always shows up.

Example and result

``` {r}
library(ggplot2)
library(ggradar)

df <- data.frame(Name="Object_xx",Zustand=0.8, V1=0.5, V2=0.5, V3=0.5, V4=0.363)
r_chart <- ggradar(plot.data=df,
                   font.radar = "Helvetica",
                   grid.label.size = 4,
                   axis.label.size = 4,
                   plot.legend = T
                   )
plot(r_chart)
```
gives the following result:

![rplot](https://user-images.githubusercontent.com/20453340/39914458-68066c72-5505-11e8-83d2-30e2261c5048.png)

However, what I want is this:

![rplot_copy](https://user-images.githubusercontent.com/20453340/39914523-869dc220-5505-11e8-9b54-d734892e3e5a.png)

**Comment by xl0418** [comment]
Hi, you may remove the legend by setting `+theme(legend.position = 'none') `, although it is a stupid way. But it works...
