### ISSUE TITLE
Example fails on MacOS

### ISSUE THREAD

**Issue by admercs** [ricardo-bion/ggradar#18]
Example output:

```
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

Also, the Circular Air Light TTF font does not install correctly on MacOS. That is what the warnings are about.

**Comment by feiranl** [comment]
meet the same output in the Mac

**Comment by modche** [comment]
Same error message for me on
`R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6`

and with `ggplot2_3.0.0.9000`

**Comment by michaelpmcdonald** [comment]
One way to get past this is to pass the parameter `font.radar` into your function call, e.g. `font.radar = "Arial"`

**Comment by svdvliet** [comment]
> One way to get past this is to pass the parameter `font.radar` into your function call, e.g. `font.radar = "Arial"`

@ricardo-bion Can you maybe add this to the helpfile in R

**Comment by ricardo-bion** [comment]
fixed
