### ISSUE TITLE
Issues with ggradar

### ISSUE THREAD

**Issue by RenatoPdosSantos** [ricardo-bion/ggradar#2]
Hi, Ricardo.

I'm starting to use your package ggradar and I'm having a few problems:
1) I can't reduce the size of the legend labels. I've used legend.text.size=5 with no avail.
2) I can't set a legend title. I've tried legend.title with no result as well.

Despite of that, it's a great package.

Renato

**Comment by muranyia** [comment]
I can confirm that legend.text.size doesn't work.

**Comment by slightlydeviant** [comment]
It appears in the source code that the legend title is an `element_blank()` object.

Line 269: `theme(legend.title=element_blank())`

As a work around, you can add standard ggplot layers to your ggradar object. To solve the issues above, you can add the ggplot theme layer.

For example

```
ggradar(some_data,
        legend.title = "Title") +
  theme(legend.text = element_text(size = 8))
```

**Comment by gousiosg** [comment]
#4 fixes this, hope it gets accepted by the author.
