### ISSUE TITLE
ggradar not working

### ISSUE THREAD

**Issue by jlmborges** [ricardo-bion/ggradar#57]
It seams that something is wrong with the current version of R. 
Running the example 

library(ggradar)
library(dplyr)
library(scales)
library(tibble)

mtcars_radar <- mtcars %>% 
    as_tibble(rownames = "group") %>% 
    mutate_at(vars(-group), rescale) %>% 
    tail(4) %>% 
    select(1:10)

results in the follow image
![Rplot](https://user-images.githubusercontent.com/45044810/232435308-a4464205-e79f-46c5-8442-13dd761b358e.png)

I had some examples of my own that are not running well now.

**Comment by lf-araujo** [comment]
Can confirm behavior.

**Comment by ricardo-bion** [comment]
@tonyy0001 FYI. It seems that this issue was introduced with your recent PR. I will revert back to the previous version if we can't get it fixed.

**Comment by tonyy01** [comment]
Oh! This is because I didn't multiply it with 100% and the values are so small. I will fix that now!

**Comment by jlmborges** [comment]
The command ggradar ( mtcars_radar ) is now working. Thanks.

But I still am having a problem with the parameters.
I keep getting the error of the type 'unused arguments'

With the example on the package page I get:
"Error in ggradar(., font.radar = "Calibri") : 
  unused argument (font.radar = "Calibri")"

With the following instruction :

ggradar( na.omit(ds_w) ,   centre.y = min_value , grid.mid = min_value + ( max_value - min_value ) / 2 , grid.max = max_value , group.line.width = 0.5 , group.point.size = 1.5 , fill = TRUE, fill.alpha = 0.05 , plot.title = "yearly return - radar plot", axis.label.size = 2, legend.text.size = 6 , legend.position = "bottom"  )

I get the error:

Error in ggradar(na.omit(ds_w), centre.y = min_value, grid.mid = min_value +  : 
  unused arguments (centre.y = -0.5 , grid.mid = 0.05 , grid.max =0.6 , group.line.width = 0.5, group.point.size = 1.5, fill = TRUE, fill.alpha = 0.05, plot.title = "yearly return - radar plot")

**Comment by tonyy01** [comment]
> The command ggradar ( mtcars_radar ) is now working. Thanks.
> 
> But I still am having a problem with the parameters. I keep getting the error of the type 'unused arguments'
> 
> With the example on the package page I get: "Error in ggradar(., font.radar = "Calibri") : unused argument (font.radar = "Calibri")"
> 
> With the following instruction :
> 
> ggradar( na.omit(ds_w) , centre.y = min_value , grid.mid = min_value + ( max_value - min_value ) / 2 , grid.max = max_value , group.line.width = 0.5 , group.point.size = 1.5 , fill = TRUE, fill.alpha = 0.05 , plot.title = "yearly return - radar plot", axis.label.size = 2, legend.text.size = 6 , legend.position = "bottom" )
> 
> I get the error:
> 
> Error in ggradar(na.omit(ds_w), centre.y = min_value, grid.mid = min_value + : unused arguments (centre.y = -0.5 , grid.mid = 0.05 , grid.max =0.6 , group.line.width = 0.5, group.point.size = 1.5, fill = TRUE, fill.alpha = 0.05, plot.title = "yearly return - radar plot")

Hello Mr. Borges, it's a pleasure to meet you! I apologize for any confusion that may arise when people use my function, as the variables in my function are quite different from the original version to improve readability and accommodate new features. Without these changes, the names of the new features might be difficult to understand or even mask the original ones. Therefore, I created a separate R file for my function instead of modifying the original one. I'm sorry for any inconvenience this may have caused.

With that said, I would love to hear your thoughts on my code. If you find it difficult to adjust, I am more than happy to make improvements or add exception messages if needed. Thank you for your time.

**Comment by jlmborges** [comment]
It would help some instructions stating the goal and how to use each parameter. 
I am going to try it a will let you know

**Comment by ricardo-bion** [comment]
@tonyy0001 Can we make the code backward compatible? If we can't make that happen, I will probably have to revert back to the previous version of the package.

**Comment by tonyy01** [comment]
> @tonyy0001 Can we make the code backward compatible? If we can't make that happen, I will probably have to revert back to the previous version of the package.

Yeah, yeah please do it. I didn't realize you have made a release.

**Comment by tonyy01** [comment]
> It would help some instructions stating the goal and how to use each parameter. I am going to try it a will let you know

Hope to hear from you soon!

**Comment by ShixiangWang** [comment]
two same functions exist in the package and make the function in the ggradar2 is evaluated lately, all code written by the function in the ggradar.R is not working anymore.

https://github.com/ricardo-bion/ggradar/blob/master/R/ggradar.R
https://github.com/ricardo-bion/ggradar/blob/master/R/ggradar2.R

**Comment by tonyy01** [comment]
> two same functions exist in the package and make the function in the ggradar2 is evaluated lately, all code written by the function in the ggradar.R is not working anymore.
> 
> https://github.com/ricardo-bion/ggradar/blob/master/R/ggradar.R https://github.com/ricardo-bion/ggradar/blob/master/R/ggradar2.R

@ricardo-bion Could you please change my function name? I am new to the compatibility of R packages and functions and I am sorry for the error that I generate.

**Comment by tonyy01** [comment]
@ricardo-bion @ShixiangWang I am sorry for the compatibility problem that I generate. I changed the function name to ggradar_alternative and opened #59 . I hope it will work.

**Comment by ricardo-bion** [comment]
Should be fixed.
