### ISSUE TITLE
Error: 'plot.data' contains value(s) > grid.max

### ISSUE THREAD

**Issue by diplodata** [ricardo-bion/ggradar#7]
Hi Ricardo - could you possibly advise what I'm doing wrong here?

```
require(ggplot2); require(ggradar); require(dplyr); require(tidyr)
dat = data.frame(month = rep(month.abb, 3) %>% factor(month.abb), group = rep(c('A','B','C'), each=12),
                 val = c(sample(11:22), sample(21:32), sample(31:42))) %>% spread(month, val)
dat
#>   group Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
#> 1     A  11  20  15  21  17  19  13  14  12  18  22  16
#> 2     B  21  31  27  24  22  26  32  29  28  25  30  23
#> 3     C  32  36  40  31  35  42  33  37  39  41  34  38
ggradar(dat)
#> [1] "Error: 'plot.data' contains value(s) > grid.max"
```

**Comment by Torenable** [comment]
You need to rescale your data before passing to `ggradar`.

Try this

```r
library(scales)
dat %>% 
  mutate_each(funs(rescale), -group) %>%
  ggradar()
```

**Comment by drexvictor** [comment]
Please help with the following.

`> test2
    Computer Science   English     Hindi     Maths   Science Social Science Tamil
FA1        0.9000000 0.8000000 1.0000000 1.0000000 1.0000000      1.0000000  1.00
FA2        0.8000000 0.6000000 0.4000000 0.5000000 0.6000000      0.7000000  0.50
FA3        0.8000000 1.0000000 2.0000000 1.0000000 1.0000000      1.0000000  0.00
FA4        0.6500000 0.8000000 0.9000000 0.2500000 0.6700000      0.4600000  0.61
SA1        0.7333333 0.7666667 0.8333333 0.3333333 0.7666667      0.6000000  0.75
SA2        0.6166667 0.6766666 0.4000000 0.4566667 0.6433333      0.6866667  0.71
> ggradar(test2)
[1] "Error: 'plot.data' contains value(s) > grid.max"`

**Comment by drexvictor** [comment]
Found the error. Hindi - FA3 has a value 2 and that is the cause of it. It should be 1
