### ISSUE TITLE
Circular Air-Light 3.46.45 PM.ttf

### ISSUE THREAD

**Issue by eulertech** [ricardo-bion/ggradar#8]
The font can't be downloaded.

**Comment by JavierFajado** [comment]
Same problem here :(

**Comment by ghost** [comment]
The font is unavailable from your dropbox site. Could you let us know where to download.

**Comment by ricardo-bion** [comment]
fixed here: 

```download.file("https://github.com/ricardo-bion/ggtech/blob/master/Circular%20Air-Light%203.46.45%20PM.ttf", "~/Circular Air-Light 3.46.45 PM.ttf", method="curl")```
